### ISSUE TITLE
Crash during delete

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#149]
I attempted a `terraform destroy` and received the following crash. On a subsequent `terraform destroy` there was no error.

It looks like `metal.ignoreResponseErrors` may not be handling a null value correctly.

```
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

metal_vlan.private_vlans[1]: Destroying... [id=efffcb9b-b338-42ad-a0f5-15bff1e35f42]
metal_vlan.private_vlans[0]: Destroying... [id=d97e954a-a815-4b55-b27e-a1e74e102b44]
metal_device_network_type.esxi_hosts[0]: Destroying... [id=1170631c-4959-4a83-b792-a8a59f449826]
metal_vlan.private_vlans[2]: Destroying... [id=80bcb037-be64-4630-bfd7-0220d2e7b18d]
metal_vlan.public_vlans[0]: Destroying... [id=a0043d83-2b7e-41cd-907b-f417ed663416]
metal_device_network_type.esxi_hosts[1]: Destroying... [id=7d41174f-abbb-4e2a-a5f5-94730bd83750]
metal_device_network_type.esxi_hosts[1]: Destruction complete after 0s
metal_device_network_type.esxi_hosts[0]: Destruction complete after 0s
metal_device.esxi_hosts[0]: Destroying... [id=1170631c-4959-4a83-b792-a8a59f449826]
metal_device.esxi_hosts[1]: Destroying... [id=7d41174f-abbb-4e2a-a5f5-94730bd83750]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-metal_v2.0.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18cb400]

goroutine 29 [running]:
github.com/equinix/terraform-provider-metal/metal.ignoreResponseErrors.func1(0x0, 0x1bef1a0, 0xc0001d7fb0, 0xc0008541c0, 0x1bef1a0)
	github.com/equinix/terraform-provider-metal/metal/errors.go:144 +0x60
github.com/equinix/terraform-provider-metal/metal.resourceMetalVlanDelete(0xc00017e5b0, 0x19cc7c0, 0xc0005a8500, 0x24, 0x21123a0)
	github.com/equinix/terraform-provider-metal/metal/resource_metal_vlan.go:129 +0x12c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00058d700, 0xc0003ac2d0, 0xc0003aa180, 0x19cc7c0, 0xc0005a8500, 0x100df01, 0x20, 0x1a3d5a0)
	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:278 +0x4a6
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00058d880, 0xc0006378e8, 0xc0003ac2d0, 0xc0003aa180, 0x21123a0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/provider.go:289 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0005860f0, 0x1c00e90, 0xc000392720, 0xc000758120, 0xc0005860f0, 0xc000392720, 0xc0003bba50)
	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1a68a40, 0xc0005860f0, 0x1c00e90, 0xc000392720, 0xc000758060, 0x0, 0x1c00e90, 0xc000392720, 0xc0003bc000, 0xb1)
	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000166160, 0x1c09078, 0xc0005ef380, 0xc0005ea600, 0xc000117680, 0x20d3e80, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000166160, 0x1c09078, 0xc0005ef380, 0xc0005ea600, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00058a190, 0xc000166160, 0x1c09078, 0xc0005ef380, 0xc0005ea600)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-metal_v2.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by displague** [comment]
I just noticed this says "2.0.1" and not "2.1.0".
This was most likely https://github.com/equinix/terraform-provider-metal/issues/89.
