### ISSUE TITLE
crash when IP reservation is filtered by facility and no facility is returned

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#162]
An IP reservation may not include a Facility and 
https://github.com/equinix/terraform-provider-metal/blob/main/metal/datasource_metal_precreated_ip_block.go#L91-L102 does not handle that.

```
panic: runtime error: invalid memory address or nil pointer dereference
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x18a67fb]
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0:
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: goroutine 69 [running]:
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: github.com/equinix/terraform-provider-metal/metal.dataSourceMetalPreCreatedIPBlockRead(0xc00020cd90, 0x19d8080, 0xc00013a280, 0xc00020cd90, 0x0)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	github.com/equinix/terraform-provider-metal/metal/datasource_metal_precreated_ip_block.go:95 +0x39b
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000158580, 0xc00095c280, 0x19d8080, 0xc00013a280, 0xc000178798, 0x1, 0x0)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:398 +0x91
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000054280, 0xc0003ad9a8, 0xc00095c280, 0xc00095c280, 0x0, 0x0)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/provider.go:446 +0x8f
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e048, 0x1c0e290, 0xc0009b6630, 0xc000540c40, 0xc00000e048, 0xc0009b6630, 0xc0006a2a50)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:1036 +0x42d
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1a74460, 0xc00000e048, 0x1c0e290, 0xc0009b6630, 0xc00019dc80, 0x0, 0x1c0e290, 0xc0009b6630, 0xc0004b2000, 0xef)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3225 +0x214
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d0160, 0x1c16478, 0xc000582a80, 0xc0000f1d00, 0xc00010f020, 0x20e3ed0, 0x0, 0x0, 0x0)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: google.golang.org/grpc.(*Server).handleStream(0xc0001d0160, 0x1c16478, 0xc000582a80, 0xc0000f1d00, 0x0)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000042290, 0xc0001d0160, 0x1c16478, 0xc000582a80, 0xc0000f1d00)
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-07-21T14:57:45.280-0500 [DEBUG] plugin.terraform-provider-metal_v2.1.0: 	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5
2021-07-21T14:57:45.282-0500 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/equinix/metal/2.1.0/darwin_amd64/terraform-provider-metal_v2.1.0 pid=74821 error="exit status 2"
```

**Comment by t0mk** [comment]
@displague Yeah, this happens where there's an elastic block created in metro (a newly created block), and user declares the datasource wih specified facility like
```
data "metal_precreated_ip_block" "test" {
  project_id = metal_project.test.id
  address_family = 4
  public = true
  facility = "sv15"
}
```

I will fix it, but another problem here is that the elastic block is processed in datasource called "precreated_ip_block", which was (unfortunately) intended to mean the blocks which are created when a new device is provisioned (private ipv4 and public ipv6 block in devices facility).

It seems that the datasources for IP blcoks in our provider are a bit confusing. We have

* the aforementioned `metal_precreated_ip_block` which allows to query by global and public flags, facility, metro and address_family. It requ
* `metal_reserved_ip_block` whcih allows to query by `id` and `ip_address` belonging to the block.
* (both above actually list all the IP blocks, precreated and explicitly reserved. Both also return first matching block only, and ignore if there's more matching)
* `metal_ip_block_ranges` which allows to query by `facility` and `metro` and returns CIDR expressions for existing address ranges

IMO we should merge datasources `metal_precreated_ip_block` and `metal_reserved_ip_block` into datasource `metal_ip_block`. It will be a bit wild to validate the input parameter combinations, and query by all of
* id
* global and public flags
* facility
* metro 
* address_family
* IP address belonging to the block
 
.. but maybe it will make things easier for the user to have only one means to query for a single IP block.

**Comment by displague** [comment]
This makes sense, I think `metal_ip_block` would effectively be `metal_reserved_ip_block` with the extra `metal_precreated_ip_block` filter parameters.

I think we would also want to filter by device_id, for assigned addresses filtering and https://github.com/equinix/terraform-provider-metal/issues/160 (filter by gateway id, this may not be present in the API response yet). (I believe assignments device href is included in the IP response).

We would deprecate the two others.

It is common for a provider to offer a single result data sources and a multiple result data source with a plural name, which we have in `metal_ip_block_ranges`.
